### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by shmuelbarkin** [meyerauslander/table-of-contents#1]
When the page loads the following error is being generated
`Uncaught ReferenceError: classes_1 is not defined` open the console to view.
<img width="1435" alt="2018-05-17_0913" src="https://user-images.githubusercontent.com/22505270/40162138-393c5ffc-59b3-11e8-97b6-b96e56600c2a.png">

**Comment by meyerauslander** [comment]
Fixed

**Comment by erichuang2015** [comment]
Uncaught ReferenceError: classes_1 is not defined

wordpress version 4.9.4

**Comment by meyerauslander** [comment]
This problem should be fixed.
