### ISSUE TITLE
Margin for empty TOC

### ISSUE THREAD

**Issue by shmuelbarkin** [meyerauslander/table-of-contents#2]
Where there are no results for the TOC the TOC widget is not displayed. While the text itself is not displaying there still is margin that is added above the next widget. This space should be removed.
<img width="1203" alt="space of empty toc" src="https://user-images.githubusercontent.com/22505270/40162248-a254fc6a-59b3-11e8-914b-bb2e0713908e.png">

**Comment by meyerauslander** [comment]
Fixed
